# .github/workflows/static-web-apps.yml
name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    # ---------- Pobranie repozytorium ----------
    - name: Checkout repository
      uses: actions/checkout@v3

    # ---------- Konfiguracja Node + cache ----------
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: npm
        cache-dependency-path: Frontend/FinAppFront/package-lock.json

    # ---------- Budowa front-endu (Angular) ----------
    - name: Build Angular app
      working-directory: Frontend/FinAppFront
      run: |
        npm ci
        npm run build -- --configuration production   # ➜ dist/fin-app-front

    # (opcjonalnie) podgląd artefaktów builda
    - name: Debug – zawartość builda
      working-directory: Frontend/FinAppFront
      run: ls -R dist

    # ---------- Konfiguracja .NET + budowa Azure Functions ----------
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Build API Functions
      working-directory: Backend/Store
      run: |
        dotnet restore
        dotnet build --configuration Release

    # ---------- Deployment do Azure Static Web Apps ----------
    - name: Deploy to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        # token z portalu Azure → Settings → Deployment Token
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        # token GitHub – potrzebny do komentarzy w PR-ach
        repo_token: ${{ secrets.GITHUB_TOKEN }}

        action: upload

        # ------- FRONT-END -------
        # katalog z GOTOWYMI plikami (zawiera index.html)
        app_location: Frontend/FinAppFront/dist/fin-app-front
        skip_app_build: true
        output_location: ''         # przy skip_app_build musi być pusty

        # ------- BACK-END (.NET Functions) -------
        api_location: Backend/Store
        skip_api_build: true
