name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Build Angular App
        working-directory: 'Frontend/FinAppFront'
        run: |
          npm ci
          npm run build -- --configuration production

      - name: Debug pokaż pliki builda
        working-directory: 'Frontend/FinAppFront'
        run: |
          ls -R dist/FinAppFront

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Build API Functions
        working-directory: 'Backend/Store'
        run: |
          dotnet restore
          dotnet build --configuration Release

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: 'Frontend/FinAppFront'
          api_location: 'Backend/Store'
          skip_app_build: true
          skip_api_build: true
          output_location: 'Frontend/FinAppFront/dist/FinAppFront'
