# ===============================================================
#  Build & Deploy:  Angular front-end  +  .NET 8 Web API  →  Azure App Service
#  Plan: Free (F1)  •  Runtime stack w portalu:  .NET 8 (LTS) / Windows
# ===============================================================

name: Build and deploy FinApp to Azure Web App (F1)

on:
  push:
    branches: [ main ]          # uruchamia się po każdym pushu do main
  workflow_dispatch:            # pozwala odpalić ręcznie z karty Actions

env:
  # katalogi
  ANGULAR_DIR: Frontend/FinAppFront
  API_CSPROJ:  src/Store/Store.csproj
  PUBLISH_DIR: publish

#─────────────────────────────────────────────────────────────────
# 1) BUILD
#─────────────────────────────────────────────────────────────────
jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
    # ① checkout
    - name: Checkout repository
      uses: actions/checkout@v4

    # ② Node – potrzebny do budowy Angulara
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18.x

    # ③ .NET 8 SDK
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x          # projekt już ma <TargetFramework>net8.0

    # ④ Build Angular → dist/fin-app-front
    - name: Build Angular (front-end)
      working-directory: ${{ env.ANGULAR_DIR }}
      run: |
        npm ci
        npm run build -- --configuration production

    # ⑤ Kopiujemy dist do wwwroot projektu API
    - name: Copy Angular assets to wwwroot
      shell: pwsh
      run: |
        New-Item -Force -ItemType Directory "$(Split-Path '${{ env.API_CSPROJ }}')/wwwroot"
        robocopy ${{ env.ANGULAR_DIR }}/dist/fin-app-front `
                 $(Split-Path '${{ env.API_CSPROJ }}')/wwwroot `
                 /E /NJH /NJS /NDL

    # ⑥ dotnet build solution / csproj
    - name: dotnet build
      run: dotnet build ${{ env.API_CSPROJ }} -c Release

    # ⑦ publish (self-contained artefakt)
    - name: dotnet publish
      run: dotnet publish ${{ env.API_CSPROJ }} -c Release -o ${{ env.PUBLISH_DIR }}

    # ⑧ artefakt do kolejnego joba
    - uses: actions/upload-artifact@v4
      with:
        name: finapp-artifact
        path: ${{ env.PUBLISH_DIR }}

#─────────────────────────────────────────────────────────────────
# 2) DEPLOY
#─────────────────────────────────────────────────────────────────
  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write     # OIDC log-in
      contents: read

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: finapp-artifact

    # logowanie OIDC – sekrety stworzone przez portal
    - name: Azure login (OIDC)
      uses: azure/login@v2
      with:
        client-id:       ${{ secrets.AZUREAPPSERVICE_CLIENTID_9213863F16E6412D89AFBADD35BF055E }}
        tenant-id:       ${{ secrets.AZUREAPPSERVICE_TENANTID_0FF71B2D203B4C1A8DD949B53A42CF6A }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3FC1188BDFCB4392A0BD5592CF2323F1 }}

    # zip-deploy do App Service
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name:  FinApp          # musi idealnie odpowiadać nazwie w portalu
        slot-name: Production
        package:   ${{ env.PUBLISH_DIR }}
