# .github/workflows/azure-webapps.yml
name: Build and deploy FinApp to Azure Web App (Free F1)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
#──────────────────────────────────────────────
# 1) BUILD
#──────────────────────────────────────────────
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    # ① Node jest potrzebny, bo 'dotnet publish' odpala `npm run build`
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'

    # ② Ustaw SDK **6.x**, bo projekt ma <TargetFramework>net6.0</TargetFramework>
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    # ③ Budujemy cały solution – OK
    - name: dotnet build
      run: dotnet build Backend/Store/Store.csproj -c Release

    # ④ Publish – wyjście do podkatalogu publish
    - name: dotnet publish
      run: dotnet publish Backend/Store/Store.csproj -c Release -o publish

    # ⑤ Pakujemy artefakt
    - uses: actions/upload-artifact@v4
      with:
        name: finapp-artifact
        path: publish               # tylko to, bez źródeł

#──────────────────────────────────────────────
# 2) DEPLOY
#──────────────────────────────────────────────
  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write   # OIDC
      contents: read

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: finapp-artifact

    - name: Login to Azure (OIDC)
      uses: azure/login@v2
      with:
        client-id:      ${{ secrets.AZUREAPPSERVICE_CLIENTID_9213863F16E6412D89AFBADD35BF055E }}
        tenant-id:      ${{ secrets.AZUREAPPSERVICE_TENANTID_0FF71B2D203B4C1A8DD949B53A42CF6A }}
        subscription-id:${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3FC1188BDFCB4392A0BD5592CF2323F1 }}

    - name: Deploy to Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: FinApp            # dokładnie taka nazwa jak w portalu
        package: .                  # kropka = zawartość pobranego artefaktu
        slot-name: Production
