# ===============================================================
#  Build & Deploy  –  Angular SPA + .NET 8 Web API  →  Azure App Service (F1)
# ===============================================================

name: Build and deploy FinApp to Azure Web App (F1)

on:
  push:
    branches: [ main ]      # automatycznie przy każdym pushu do main
  workflow_dispatch:        # możliwość ręcznego uruchomienia

env:
  # katalog projektu SPA / API / publish
  ANGULAR_DIR: Frontend/FinAppFront
  API_CSPROJ:  src/Store/Store.csproj
  PUBLISH_DIR: publish

#─────────────────────────────────────────────────────────────────
# 1) BUILD
#─────────────────────────────────────────────────────────────────
jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
    # ① checkout
    - name: Checkout repository
      uses: actions/checkout@v4

    # ② Node – do builda Angulara
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18.x

    # ③ .NET 8 SDK
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    # ④ Build Angular → dist/fin-app-front
    - name: Build Angular (front-end)
      working-directory: ${{ env.ANGULAR_DIR }}
      run: |
        npm ci
        npm run build -- --configuration production

    # ⑤ Kopiujemy pliki SPA do wwwroot projektu API
    - name: Copy Angular assets to wwwroot
      shell: pwsh
      run: |
        # katalog docelowy
        $dest = Join-Path -Path (Split-Path '${{ env.API_CSPROJ }}') -ChildPath 'wwwroot'
        New-Item -ItemType Directory -Force -Path $dest | Out-Null

        # kopiowanie
        robocopy "${{ env.ANGULAR_DIR }}/dist/fin-app-front" "$dest" /E /NJH /NJS /NDL

    # ⑥ Budujemy API
    - name: dotnet build
      run: dotnet build ${{ env.API_CSPROJ }} -c Release

    # ⑦ Publish
    - name: dotnet publish
      run: dotnet publish ${{ env.API_CSPROJ }} -c Release -o ${{ env.PUBLISH_DIR }}

    # ⑧ Artefakt do joba deploy
    - uses: actions/upload-artifact@v4
      with:
        name: finapp-artifact
        path: ${{ env.PUBLISH_DIR }}

#─────────────────────────────────────────────────────────────────
# 2) DEPLOY
#─────────────────────────────────────────────────────────────────
  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write   # OIDC
      contents: read

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: finapp-artifact

    # Logowanie do Azure przez OIDC (sekrety wygenerowane przez portal)
    - name: Azure login (OIDC)
      uses: azure/login@v2
      with:
        client-id:       ${{ secrets.AZUREAPPSERVICE_CLIENTID_9213863F16E6412D89AFBADD35BF055E }}
        tenant-id:       ${{ secrets.AZUREAPPSERVICE_TENANTID_0FF71B2D203B4C1A8DD949B53A42CF6A }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3FC1188BDFCB4392A0BD5592CF2323F1 }}

    # Deploy ZIP-em do App Service
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name:  FinApp          # dokładnie jak w portalu
        slot-name: Production
        package:   ${{ env.PUBLISH_DIR }}
